# Generated by Django 5.0.6 on 2024-07-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
